# Generated by Django 4.1.3 on 2022-11-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='x-tudo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
            ],
        ),
    ]
